export const doctors = [
  {
    id: "dr-ayan-patra",
    name: "Dr. Ayan Patra",
    qualification: "B.A.M.S., M.D. (Ayu)",
    role: "Assistant Professor, Consultant Ayurvedic Physician",
    experience: "5+ years",
    photo: "/images/dr-ayan.jpg",
    bio: "Dr. Ayan Patra is a highly qualified Ayurvedic physician with over 5 years of clinical experience. As an Assistant Professor and Consultant, he combines classical Ayurvedic principles with modern medical understanding to deliver personalized, root-cause treatments for his patients.",
    specialities: ["Digestive & Metabolic Disorders", "Musculoskeletal & Joint Diseases", "Menstrual & Hormonal Disorders"],
  },
  {
    id: "dr-swati-prasad",
    name: "Dr. Swati Prasad",
    qualification: "B.A.M.S., M.D. (Ayu)",
    role: "Assistant Professor, Consultant Ayurvedic Physician",
    experience: "5+ years",
    photo: "/images/dr-swati.jpg",
    bio: "Dr. Swati Prasad brings over 5 years of dedicated practice in Ayurvedic medicine. As an Assistant Professor and Consultant, she specializes in women's health, metabolic conditions, and lifestyle management, offering compassionate care grounded in classical Ayurvedic wisdom.",
    specialities: ["Menstrual & Hormonal Disorders", "Digestive & Metabolic Disorders", "Anorectal Disorders"],
  },
];

export const specialities = [
  {
    id: "digestive-metabolic",
    category: "Digestive & Metabolic Disorders",
    icon: "🫃",
    image: "/images/speciality-digestive.jpg",
    conditions: [
      {
        id: "grahani",
        name: "Grahani",
        englishName: "Irritable Bowel Syndrome (IBS) & Chronic Malabsorption",
        sanskritName: "Grahani",
        description: "A condition affecting the small intestine (grahani), characterized by irregular digestion, abdominal discomfort, bloating, and malabsorption of nutrients.",
        symptoms: ["Chronic diarrhea or constipation", "Abdominal cramping and bloating", "Food intolerance", "Fatigue after meals", "Poor nutrient absorption"],
        approach: "Ayurvedic management focuses on restoring Agni (digestive fire) through dietary modifications, herbal formulations like Kutaja and Bilva, Panchakarma therapies, and lifestyle adjustments tailored to your Dosha constitution.",
      },
      {
        id: "amlapitta",
        name: "Amlapitta",
        englishName: "GERD & Hyperacidity",
        sanskritName: "Amlapitta",
        description: "Excess Pitta in the stomach causing hyperacidity, heartburn, and acid reflux. A highly treatable condition through Pitta-pacifying protocols.",
        symptoms: ["Heartburn and acid reflux", "Nausea and sour belching", "Chest discomfort", "Bitter taste in mouth", "Loss of appetite"],
        approach: "Treatment includes Pitta-shamaka herbs like Yashtimadhu, Amalaki, and Shatavari, along with cooling dietary practices, stress management, and specific Panchakarma procedures when indicated.",
      },
      {
        id: "vrishya-prameha",
        name: "Vrishya / Prameha",
        englishName: "Metabolic Syndrome & Type 2 Diabetes (Early–Moderate)",
        sanskritName: "Prameha",
        description: "Metabolic imbalances including early to moderate Type 2 Diabetes, insulin resistance, and related metabolic syndrome conditions.",
        symptoms: ["Increased thirst and urination", "Unexplained weight changes", "Fatigue and lethargy", "Slow wound healing", "Numbness in extremities"],
        approach: "Holistic management through Kapha-reducing diet, anti-diabetic herbs (Gurmar, Methi, Jamun), regular exercise protocols (Vyayama), and metabolic-resetting Panchakarma therapies.",
      },
      {
        id: "yakrit-roga",
        name: "Yakrit Roga",
        englishName: "Fatty Liver Disease (NAFLD) & Mild Hepatic Dysfunction",
        sanskritName: "Yakrit Roga",
        description: "Liver disorders including Non-Alcoholic Fatty Liver Disease and mild hepatic dysfunction, addressed through liver-restorative Ayurvedic protocols.",
        symptoms: ["Fatigue and weakness", "Right upper abdominal discomfort", "Elevated liver enzymes", "Loss of appetite", "Nausea"],
        approach: "Liver-restorative herbs like Bhringraj, Kalmegh, and Punarnava, combined with Pitta-Kapha balancing diet, detoxification therapies, and lifestyle modifications for hepatic health.",
      },
    ],
  },
  {
    id: "musculoskeletal",
    category: "Musculoskeletal & Joint Diseases",
    icon: "",
    image: "/images/speciality-joints.jpg",
    conditions: [
      {
        id: "sandhivata",
        name: "Sandhivata",
        englishName: "Osteoarthritis",
        sanskritName: "Sandhivata",
        description: "Degenerative joint disease caused by Vata vitiation in the joints, leading to pain, stiffness, and reduced mobility.",
        symptoms: ["Joint pain and stiffness", "Reduced range of motion", "Joint swelling", "Cracking sounds in joints", "Morning stiffness"],
        approach: "Vata-pacifying treatments including Abhyanga (oil massage), Janu Basti (knee pooling), herbal poultices, internal medicines like Mahayogaraj Guggul, and gentle yoga therapy.",
      },
      {
        id: "amavata",
        name: "Amavata",
        englishName: "Rheumatoid Arthritis",
        sanskritName: "Amavata",
        description: "An autoimmune inflammatory joint condition caused by accumulation of Ama (toxins) combined with Vata vitiation.",
        symptoms: ["Symmetrical joint pain and swelling", "Morning stiffness lasting >1 hour", "Fatigue and fever", "Joint deformity in advanced stages", "Loss of appetite"],
        approach: "Comprehensive Ama-pachana (toxin elimination) through Langhana, specific herbs like Guggulu and Shallaki, Panchakarma (especially Basti), and anti-inflammatory dietary protocols.",
      },
      {
        id: "vatarakta",
        name: "Vatarakta",
        englishName: "Gout",
        sanskritName: "Vatarakta",
        description: "A metabolic disorder characterized by uric acid accumulation causing severe joint inflammation, typically starting in the big toe.",
        symptoms: ["Sudden severe joint pain", "Red, hot, swollen joints", "Typically affects big toe first", "Recurrent attacks", "Tophi formation in chronic cases"],
        approach: "Blood-purifying herbs like Manjistha and Guduchi, Vata-Rakta shamaka treatments, dietary restrictions on purine-rich foods, and targeted Panchakarma for metabolic correction.",
      },
      {
        id: "gridhrasi",
        name: "Gridhrasi",
        englishName: "Sciatica & Lumbar Radiculopathy",
        sanskritName: "Gridhrasi",
        description: "Pain radiating along the sciatic nerve from the lower back through the hips and down the leg, caused by Vata obstruction.",
        symptoms: ["Shooting pain down the leg", "Lower back pain", "Numbness or tingling", "Muscle weakness in leg", "Pain worsens with sitting"],
        approach: "Kati Basti (lower back oil pooling), targeted Abhyanga, herbal medicines like Yograj Guggul, specific yoga postures, and in severe cases, Panchakarma including Basti therapy.",
      },
      {
        id: "kativata-grivastambha",
        name: "Kativata / Grivastambha",
        englishName: "Cervical & Lumbar Spondylosis",
        sanskritName: "Kativata / Grivastambha",
        description: "Degenerative conditions of the cervical and lumbar spine causing pain, stiffness, and nerve compression symptoms.",
        symptoms: ["Neck or lower back stiffness", "Radiating pain to arms or legs", "Headaches (cervical)", "Numbness in fingers or toes", "Reduced spinal flexibility"],
        approach: "Localized treatments like Griva Basti and Kati Basti, herbal oils for massage, spinal strengthening yoga, internal Vata-pacifying medicines, and posture correction guidance.",
      },
    ],
  },
  {
    id: "anorectal",
    category: "Anorectal Disorders",
    icon: "🩺",
    image: "/images/speciality-anorectal.jpg",
    conditions: [
      {
        id: "arsha",
        name: "Arsha",
        englishName: "Hemorrhoids / Piles",
        sanskritName: "Arsha",
        description: "Swollen veins in the lower rectum and anus, classified in Ayurveda into multiple types based on Dosha involvement.",
        symptoms: ["Bleeding during bowel movements", "Painful or painless swelling", "Itching around anus", "Discomfort while sitting", "Prolapse in advanced stages"],
        approach: "Classification-based treatment with specific herbs (Nagakeshar, Haritaki), Kshara Karma (medicated alkali therapy) for suitable grades, dietary fiber optimization, and Sitz bath protocols.",
      },
      {
        id: "parikartika",
        name: "Parikartika",
        englishName: "Anal Fissures",
        sanskritName: "Parikartika",
        description: "Tears in the lining of the anal canal causing severe pain and bleeding, often associated with constipation.",
        symptoms: ["Sharp pain during bowel movements", "Bright red blood on stool", "Visible tear around anus", "Spasm of anal sphincter", "Fear of defecation"],
        approach: "Vata-shamaka treatments, healing herbs like Yashtimadhu and Triphala for gentle bowel regulation, topical medicated oils, and stool-softening dietary protocols.",
      },
      {
        id: "bhagandara",
        name: "Bhagandara",
        englishName: "Fistula-in-Ano",
        sanskritName: "Bhagandara",
        description: "An abnormal tunnel connecting the anal canal to the skin near the anus, often arising from untreated abscesses.",
        symptoms: ["Persistent discharge near anus", "Recurrent abscess formation", "Pain and swelling", "Foul-smelling discharge", "Fever during infection"],
        approach: "Kshara Sutra therapy (medicated thread treatment) — a highly effective Ayurvedic surgical approach — combined with wound-healing herbs, antibacterial formulations, and post-procedure care protocols.",
      },
    ],
  },
  {
    id: "menstrual-hormonal",
    category: "Menstrual & Hormonal Disorders",
    icon: "🌸",
    image: "/images/speciality-hormonal.jpg",
    conditions: [
      {
        id: "pcos-pcod",
        name: "PCOS/PCOD",
        englishName: "Artava Kshaya / Pushpaghani Jataharini",
        sanskritName: "Artava Kshaya",
        description: "Polycystic Ovarian Syndrome/Disorder — a hormonal imbalance affecting women of reproductive age, managed through Ayurvedic metabolic and hormonal balancing.",
        symptoms: ["Irregular or absent periods", "Weight gain and difficulty losing weight", "Excessive hair growth (hirsutism)", "Acne and oily skin", "Fertility challenges"],
        approach: "Kapha-Vata pacifying protocols, hormonal-balancing herbs like Shatavari, Lodhra, and Ashoka, lifestyle modifications including specific exercise routines, and Panchakarma for metabolic reset.",
      },
      {
        id: "dysmenorrhea",
        name: "Kashtartava",
        englishName: "Dysmenorrhea (Painful Periods)",
        sanskritName: "Kashtartava",
        description: "Painful menstrual periods caused by Vata obstruction in the reproductive channels, affecting quality of life significantly.",
        symptoms: ["Severe cramping during periods", "Lower back and thigh pain", "Nausea and headaches", "Fatigue and mood changes", "Pain starting 1-2 days before period"],
        approach: "Vata-pacifying treatments including warm Abhyanga, specific herbs like Dashamoola and Ashoka, uterine-toning formulations, dietary warmth, and targeted yoga practices.",
      },
      {
        id: "amenorrhea",
        name: "Nashtartava",
        englishName: "Amenorrhea (Absent Periods)",
        sanskritName: "Nashtartava",
        description: "Absence of menstrual periods, which can result from hormonal imbalances, stress, nutritional deficiencies, or structural issues.",
        symptoms: ["Missing three or more periods", "No period by age 15", "Sudden cessation of regular periods", "Associated weight changes", "Hair loss or excessive hair growth"],
        approach: "Comprehensive assessment of underlying cause, Rasayana therapy for reproductive tissue nourishment, herbs like Shatavari and Pushkarmool, nutritional optimization, and stress management protocols.",
      },
      {
        id: "menorrhagia",
        name: "Asrigdara / Raktapradara",
        englishName: "Menorrhagia / Abnormal Uterine Bleeding",
        sanskritName: "Asrigdara",
        description: "Excessive or prolonged menstrual bleeding, addressed through Pitta-pacifying and blood-stabilizing Ayurvedic approaches.",
        symptoms: ["Bleeding lasting more than 7 days", "Soaking through pads hourly", "Large blood clots", "Fatigue and weakness (anemia)", "Pelvic pain"],
        approach: "Pitta-Rakta shamaka herbs like Lodhra, Nagakeshar, and Praval Pishti, uterine-toning treatments, iron-rich dietary protocols, and in some cases, specific Panchakarma procedures for blood purification.",
      },
    ],
  },
];

export const clinicInfo = {
  name: "Agnivesh Ayurveda and Panchakarma Centre",
  tagline: "Your Health, Our Concern",
  phone: "+91 7044085126",
  email: "contact@agniveshayurveda.com",
  address: "Sarenga-Goaltore Road, Sarenga, Bankura - 722150, West Bengal",
  fullAddress: "Agnivesh Ayurveda and Panchakarma Centre, Sarenga-Goaltore Road, Sarenga, Bankura - 722150, West Bengal",
  googleMapsQuery: "Agnivesh+Ayurveda+and+Panchakarma+Centre+Sarenga+Bankura+722150",
  hours: [
    { day: "Monday – Friday", time: "9:00 AM – 6:00 PM" },
    { day: "Saturday", time: "9:00 AM – 2:00 PM" },
    { day: "Sunday", time: "Closed" },
  ],
};

export const whyChooseUs = [
  {
    title: "Experienced Doctor Panel",
    description: "Patient care led by highly qualified, experienced Ayurvedic physicians with deep expertise in classical principles and personalized treatment.",
    icon: "‍️",
  },
  {
    title: "Male & Female Doctors Available",
    description: "Both male and female practitioners for comfort, privacy, and ease with sensitive or gender-specific consultations.",
    icon: "",
  },
  {
    title: "Hybrid Consultation Model",
    description: "Both online (teleconsultation) for remote/busy patients and offline (in-person OPD visits) at the clinic.",
    icon: "📱",
  },
  {
    title: "Highly Affordable Care",
    description: "Authentic, top-tier holistic guidance at budget-friendly cost. Quality healthcare shouldn't break the bank.",
    icon: "💰",
  },
  {
    title: "Authentic & Root-Cause Treatment",
    description: "Natural healing, lifestyle management, and preventive care tailored to individual body constitution (Prakriti).",
    icon: "🌿",
  },
];
